dist: xenial
language: python
sudo: required

python:
  - 3.6.5

services:
  - docker

install:
  # install newer vesrsion of nmap
  - sudo apt-get install build-essential checkinstall libpcre3-dev liblua5.2-dev
  - sudo apt-get update
  - sudo apt-get install nmap

  - pip install -r requirements.txt

  # copy any required config options for the docker daemon
  #- sudo cp .travis_docker_config /etc/docker/daemon.json
  #- sudo service docker restart
  # - docker image build --tag checkpot .

script:
  - python containers/build_all.py && python ci_automated_tests.py
